[package]
name = "jam"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
daggy = "0.8.0"
either = "1.8.0"
radix_trie = "0.2.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
